- name: setup directories for vim packages and colors
  command: mkdir -p ~/.vim/autoload ~/.vim/bundle
  command: rm -rf ~/.vim/bundle/*

- name: setup vim pathogen
  get_url: url=https://raw.github.com/tpope/vim-pathogen/master/autoload/pathogen.vim  
           dest={{ home }}/.vim/autoload


- name: solarized setup
  git: repo="git://github.com/altercation/vim-colors-solarized.git" 
       dest={{ home }}/.vim/bundle/vim-colors-solarized
       
